#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("VoteAnalyzer.Resource", IsApplication=true)]

namespace VoteAnalyzer
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int cardBackgroundColor = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int cardCornerRadius = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int cardElevation = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int cardMaxElevation = 2130771971;
			
			// aapt resource value: 0x7f010005
			public const int cardPreventCornerOverlap = 2130771973;
			
			// aapt resource value: 0x7f010004
			public const int cardUseCompatPadding = 2130771972;
			
			// aapt resource value: 0x7f010006
			public const int contentPadding = 2130771974;
			
			// aapt resource value: 0x7f01000a
			public const int contentPaddingBottom = 2130771978;
			
			// aapt resource value: 0x7f010007
			public const int contentPaddingLeft = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int contentPaddingRight = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int contentPaddingTop = 2130771977;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060000
			public const int cardview_dark_background = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int cardview_light_background = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int cardview_shadow_end_color = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int cardview_shadow_start_color = 2131099651;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f070000
			public const int cardview_compat_inset_shadow = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int cardview_default_elevation = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int cardview_default_radius = 2131165186;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int congress = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int corruption = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int elections = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int first = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int head = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int home = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Logo = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int logo_transparent = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int logooriginal = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int magnifier = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int mark = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int name = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int party = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int president = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int rank = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int role = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int roundButton = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int second = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int senate = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int sequence = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int third = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int voting = 2130837525;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090011
			public const int button1 = 2131296273;
			
			// aapt resource value: 0x7f090020
			public const int button10 = 2131296288;
			
			// aapt resource value: 0x7f090017
			public const int button11 = 2131296279;
			
			// aapt resource value: 0x7f090018
			public const int button12 = 2131296280;
			
			// aapt resource value: 0x7f090019
			public const int button13 = 2131296281;
			
			// aapt resource value: 0x7f09001b
			public const int button14 = 2131296283;
			
			// aapt resource value: 0x7f090012
			public const int button2 = 2131296274;
			
			// aapt resource value: 0x7f090013
			public const int button3 = 2131296275;
			
			// aapt resource value: 0x7f090014
			public const int button4 = 2131296276;
			
			// aapt resource value: 0x7f090015
			public const int button5 = 2131296277;
			
			// aapt resource value: 0x7f090016
			public const int button6 = 2131296278;
			
			// aapt resource value: 0x7f09001e
			public const int button8 = 2131296286;
			
			// aapt resource value: 0x7f09001f
			public const int button9 = 2131296287;
			
			// aapt resource value: 0x7f09003a
			public const int editText1 = 2131296314;
			
			// aapt resource value: 0x7f09003b
			public const int editText2 = 2131296315;
			
			// aapt resource value: 0x7f09003c
			public const int editText3 = 2131296316;
			
			// aapt resource value: 0x7f090010
			public const int gridLayout1 = 2131296272;
			
			// aapt resource value: 0x7f090002
			public const int imageButton1 = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int imageButton2 = 2131296259;
			
			// aapt resource value: 0x7f090004
			public const int imageButton3 = 2131296260;
			
			// aapt resource value: 0x7f090005
			public const int imageButton4 = 2131296261;
			
			// aapt resource value: 0x7f090022
			public const int imageView1 = 2131296290;
			
			// aapt resource value: 0x7f090025
			public const int imageView2 = 2131296293;
			
			// aapt resource value: 0x7f090029
			public const int imageView3 = 2131296297;
			
			// aapt resource value: 0x7f090006
			public const int linearLayout1 = 2131296262;
			
			// aapt resource value: 0x7f090032
			public const int linearLayout10 = 2131296306;
			
			// aapt resource value: 0x7f090037
			public const int linearLayout11 = 2131296311;
			
			// aapt resource value: 0x7f090021
			public const int linearLayout12 = 2131296289;
			
			// aapt resource value: 0x7f090024
			public const int linearLayout13 = 2131296292;
			
			// aapt resource value: 0x7f090028
			public const int linearLayout14 = 2131296296;
			
			// aapt resource value: 0x7f09002f
			public const int linearLayout15 = 2131296303;
			
			// aapt resource value: 0x7f090033
			public const int linearLayout16 = 2131296307;
			
			// aapt resource value: 0x7f090049
			public const int linearLayout17 = 2131296329;
			
			// aapt resource value: 0x7f09004a
			public const int linearLayout18 = 2131296330;
			
			// aapt resource value: 0x7f09004d
			public const int linearLayout19 = 2131296333;
			
			// aapt resource value: 0x7f090007
			public const int linearLayout2 = 2131296263;
			
			// aapt resource value: 0x7f090050
			public const int linearLayout20 = 2131296336;
			
			// aapt resource value: 0x7f090053
			public const int linearLayout21 = 2131296339;
			
			// aapt resource value: 0x7f090054
			public const int linearLayout22 = 2131296340;
			
			// aapt resource value: 0x7f090058
			public const int linearLayout23 = 2131296344;
			
			// aapt resource value: 0x7f09000a
			public const int linearLayout3 = 2131296266;
			
			// aapt resource value: 0x7f09001d
			public const int linearLayout4 = 2131296285;
			
			// aapt resource value: 0x7f090023
			public const int linearLayout5 = 2131296291;
			
			// aapt resource value: 0x7f090027
			public const int linearLayout6 = 2131296295;
			
			// aapt resource value: 0x7f090000
			public const int linearLayout7 = 2131296256;
			
			// aapt resource value: 0x7f09002d
			public const int linearLayout8 = 2131296301;
			
			// aapt resource value: 0x7f09002e
			public const int linearLayout9 = 2131296302;
			
			// aapt resource value: 0x7f090040
			public const int myButton = 2131296320;
			
			// aapt resource value: 0x7f09000d
			public const int radioButton1 = 2131296269;
			
			// aapt resource value: 0x7f09000e
			public const int radioButton2 = 2131296270;
			
			// aapt resource value: 0x7f09000f
			public const int radioButton3 = 2131296271;
			
			// aapt resource value: 0x7f09000c
			public const int radioGroup1 = 2131296268;
			
			// aapt resource value: 0x7f090038
			public const int seekBar1 = 2131296312;
			
			// aapt resource value: 0x7f09001a
			public const int space1 = 2131296282;
			
			// aapt resource value: 0x7f09001c
			public const int space2 = 2131296284;
			
			// aapt resource value: 0x7f090008
			public const int textView1 = 2131296264;
			
			// aapt resource value: 0x7f090035
			public const int textView10 = 2131296309;
			
			// aapt resource value: 0x7f090041
			public const int textView11 = 2131296321;
			
			// aapt resource value: 0x7f090036
			public const int textView12 = 2131296310;
			
			// aapt resource value: 0x7f090043
			public const int textView13 = 2131296323;
			
			// aapt resource value: 0x7f090045
			public const int textView14 = 2131296325;
			
			// aapt resource value: 0x7f090047
			public const int textView15 = 2131296327;
			
			// aapt resource value: 0x7f090046
			public const int textView16 = 2131296326;
			
			// aapt resource value: 0x7f090039
			public const int textView17 = 2131296313;
			
			// aapt resource value: 0x7f090048
			public const int textView18 = 2131296328;
			
			// aapt resource value: 0x7f09004b
			public const int textView19 = 2131296331;
			
			// aapt resource value: 0x7f09000b
			public const int textView2 = 2131296267;
			
			// aapt resource value: 0x7f09004e
			public const int textView20 = 2131296334;
			
			// aapt resource value: 0x7f090051
			public const int textView21 = 2131296337;
			
			// aapt resource value: 0x7f09004c
			public const int textView22 = 2131296332;
			
			// aapt resource value: 0x7f09004f
			public const int textView23 = 2131296335;
			
			// aapt resource value: 0x7f090052
			public const int textView24 = 2131296338;
			
			// aapt resource value: 0x7f090055
			public const int textView25 = 2131296341;
			
			// aapt resource value: 0x7f090059
			public const int textView26 = 2131296345;
			
			// aapt resource value: 0x7f090056
			public const int textView27 = 2131296342;
			
			// aapt resource value: 0x7f090057
			public const int textView28 = 2131296343;
			
			// aapt resource value: 0x7f09005a
			public const int textView29 = 2131296346;
			
			// aapt resource value: 0x7f090009
			public const int textView3 = 2131296265;
			
			// aapt resource value: 0x7f09005b
			public const int textView30 = 2131296347;
			
			// aapt resource value: 0x7f090026
			public const int textView4 = 2131296294;
			
			// aapt resource value: 0x7f09002a
			public const int textView5 = 2131296298;
			
			// aapt resource value: 0x7f09002b
			public const int textView6 = 2131296299;
			
			// aapt resource value: 0x7f090034
			public const int textView7 = 2131296308;
			
			// aapt resource value: 0x7f090030
			public const int textView8 = 2131296304;
			
			// aapt resource value: 0x7f090031
			public const int textView9 = 2131296305;
			
			// aapt resource value: 0x7f090001
			public const int toolbar1 = 2131296257;
			
			// aapt resource value: 0x7f09002c
			public const int view1 = 2131296300;
			
			// aapt resource value: 0x7f09003f
			public const int view2 = 2131296319;
			
			// aapt resource value: 0x7f09003e
			public const int view3 = 2131296318;
			
			// aapt resource value: 0x7f09003d
			public const int view4 = 2131296317;
			
			// aapt resource value: 0x7f090042
			public const int view5 = 2131296322;
			
			// aapt resource value: 0x7f090044
			public const int view6 = 2131296324;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int BasicSearchLayout = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int CandidateSummaryLayout = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int ElectionSimulationLayout = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Main = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int MainLayout = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int RankingLayout = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int SelectStateLayout = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int SimulationResultLayout = 2130968583;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f080001
			public const int app_name = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int hello = 2131230720;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050001
			public const int Base_CardView = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int CardView = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int CardView_Dark = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int CardView_Light = 2131034115;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CardView = new int[] {
					16843071,
					16843072,
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978};
			
			// aapt resource value: 1
			public const int CardView_android_minHeight = 1;
			
			// aapt resource value: 0
			public const int CardView_android_minWidth = 0;
			
			// aapt resource value: 2
			public const int CardView_cardBackgroundColor = 2;
			
			// aapt resource value: 3
			public const int CardView_cardCornerRadius = 3;
			
			// aapt resource value: 4
			public const int CardView_cardElevation = 4;
			
			// aapt resource value: 5
			public const int CardView_cardMaxElevation = 5;
			
			// aapt resource value: 7
			public const int CardView_cardPreventCornerOverlap = 7;
			
			// aapt resource value: 6
			public const int CardView_cardUseCompatPadding = 6;
			
			// aapt resource value: 8
			public const int CardView_contentPadding = 8;
			
			// aapt resource value: 12
			public const int CardView_contentPaddingBottom = 12;
			
			// aapt resource value: 9
			public const int CardView_contentPaddingLeft = 9;
			
			// aapt resource value: 10
			public const int CardView_contentPaddingRight = 10;
			
			// aapt resource value: 11
			public const int CardView_contentPaddingTop = 11;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
